#!/bin/bash

if [[ -z "${NODE_ENV}" ]]; then
  echo "Please set NODE_ENV = [ production | staging | development ] before running this script."
  exit 3
fi
eee="${NODE_ENV}"

set -e

ionic cordova build browser --configuration=$eee

git add .
git commit -m 'autobuild'
git push

ssh do "cd /home/ubuntu/projects/tgm_ionic && git pull && sudo apachectl -k restart"

set +e
echo 'build tgm_ionic browser ok'
