#!/bin/bash

if [[ -z "${NODE_ENV}" ]]; then
  eee=production
  # echo "Please set NODE_ENV = [ production | staging | development ] before running this script."
  # exit 3
else
  eee="${NODE_ENV}"
fi

set -ex

cp google-services.json  platforms/android/app/
ionic cordova build android --env=$eee

git add .
git commit -m 'autobuild'
git push

##
## deploy
##
# ssh do "cd /home/ubuntu/projects/tgm_ionic && git pull && sudo apachectl -k restart"

set +ex
echo 'build tgm_ionic android ok'
